### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by blaquee** [brad-accuvant/cuckoo-modified#10]
After pulling the latest commits, I'm getting a CRITICAL ERROR related to the database, I assume because the database schema has changed, but Im not sure how to remedy this.
CRITICAL: CuckooDatabaseError: DB schema version mismatch: found 18eee46c6f81, expected 495d5a6edef3. Try to apply all migrations (cd utils/db_migration/ && alembic upgrade head).

The suggestion of using alembic doesnt work either, neither does running cuckoo.py --clean.

Should I just delete the db from the mongo cli instead?

regards

**Comment by brad-sp** [comment]
Yes, sorry about that.  The real problem was that I introduced some changes to the database without also modifying the schema id at the same time (and then creating a transition script for it).  I think the damage is already done because of that, but what I'll do is create a transition script to go from the cuckoo 1.2 db format to our db format.

**Comment by brad-sp** [comment]
I just committed https://github.com/brad-accuvant/cuckoo-modified/commit/66091031d767eeae59331167be4b8b30b51ee8a6 which should resolve the issue.  Let me know if it doesn't, thanks!

**Comment by blaquee** [comment]
Hey, thanks for the fix. Since I wasnt running this in production, i ended up just dropping the DB from the mongo CLI and let it recreate the DB, I was still getting some errors, but I think latest pull fixed this (running alembic after dropping the DB it seems)
