### ISSUE TITLE
Error when submitting RAR file (without extension)

### ISSUE THREAD

**Issue by ghost** [brad-accuvant/cuckoo-modified#104]
Error when submitting RAR file (without extension)

INFO:
File Name   6dba30763acdf93c7fb0a95aa387215c
File Size   167924 bytes
File Type   RAR archive data, v1d, os: Win32
MD5 6dba30763acdf93c7fb0a95aa387215c

2015-03-05 18:43:23,000 [root] INFO: Date set to: 03-05-15, time set to: 18:43:23
2015-03-05 18:43:23,000 [root] DEBUG: Starting analyzer from: C:\etworm
2015-03-05 18:43:23,000 [root] DEBUG: Storing results at: C:\CKijgcd
2015-03-05 18:43:23,000 [root] DEBUG: Pipe server name: \.\PIPE\aJgUNLD
2015-03-05 18:43:23,000 [root] DEBUG: No analysis package specified, trying to detect it automagically.
2015-03-05 18:43:23,000 [root] INFO: Automatically selected analysis package "rar"
2015-03-05 18:43:23,650 [root] DEBUG: Started auxiliary module Browser
2015-03-05 18:43:23,650 [root] DEBUG: Started auxiliary module Disguise
2015-03-05 18:43:23,650 [root] DEBUG: Started auxiliary module Human
2015-03-05 18:43:23,650 [root] DEBUG: Started auxiliary module Screenshots
2015-03-05 18:43:24,331 [root] ERROR: Traceback (most recent call last):
  File "C:\etworm\analyzer.py", line 919, in <module>
    success = analyzer.run()
  File "C:\etworm\analyzer.py", line 753, in run
    "{1}".format(package_name, e))
CuckooError: The package "modules.packages.rar" start function encountered an unhandled exception: No files that match pattern were found [10]: 
Cannot open C:\DOCUME~1\CBAQUS~1\LOCALS~1\Temp\6dba30763acdf93c7fb0a95aa387215c.rar
The system cannot find the file specified.
Traceback (most recent call last):
  File "C:\etworm\analyzer.py", line 919, in <module>
    success = analyzer.run()
  File "C:\etworm\analyzer.py", line 753, in run
    "{1}".format(package_name, e))
CuckooError: The package "modules.packages.rar" start function encountered an unhandled exception: No files that match pattern were found [10]: 
Cannot open C:\DOCUME~1\CBAQUS~1\LOCALS~1\Temp\6dba30763acdf93c7fb0a95aa387215c.rar
The system cannot find the file specified.

**Comment by brad-sp** [comment]
This was probably fixed via this commit: https://github.com/brad-accuvant/cuckoo-modified/pull/105 can you confirm?

**Comment by ghost** [comment]
Upon merging the #105 I still encountering the error.

Upload: (filename) a225c942408626030c50f8398a0c32de18e3a7f9abc29fc393dbb3819f1234e6
File type: RAR archive data, v1d, os: Win32

Error: Analysis failed: The package "modules.packages.rar" start function encountered an unhandled exception: No files that match pattern were found [10]: Cannot open C:{PATH}\Temp\a225c942408626030c50f8398a0c32de18e3a7f9abc29fc393dbb3819f1234e6.rar The system cannot find the file specified.
