### ISSUE TITLE
Cannot convert argument to integer

### ISSUE THREAD

**Issue by ghost** [brad-accuvant/cuckoo-modified#79]
015-06-10 15:32:50,811 [lib.api.process] INFO: Successfully executed process from path "C:\Users\Cuckoo\AppData\Local\Temp\cryptowall.bin" with arguments "" with pid 2792
2015-06-10 15:32:50,872 [lib.api.process] DEBUG: Using QueueUserAPC injection.
2015-06-10 15:32:53,247 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 2792
2015-06-10 15:32:55,247 [lib.api.process] INFO: Successfully resumed process with pid 2792
2015-06-10 15:32:55,247 [root] INFO: Added new process to list with pid: 2792
2015-06-10 15:32:55,763 [root] ERROR: Traceback (most recent call last):
  File "C:\iaxqkq\analyzer.py", line 251, in run
    response = struct.pack("II", PID, PPID)
error: cannot convert argument to integer
Traceback (most recent call last):
  File "C:\iaxqkq\analyzer.py", line 251, in run
    response = struct.pack("II", PID, PPID)
error: cannot convert argument to integer
2015-06-10 15:33:24,247 [root] INFO: Analysis timeout hit, terminating analysis.

Hello, i've got the error when i was trying samples. Every times, i've got this error message.
Cuckoo build downloaded at 12AM (Paris hours) June the 10, 2015.
Thanks.

**Comment by brad-sp** [comment]
What's the guest OS version? Can you add a log.info("Failed to obtain parent PID") just before the return None in get_parent_pid() in analyzer/windows/lib/process.py and see if it creates a log entry?

Also, is the python in the guest 32-bit, or 64-bit?

**Comment by ghost** [comment]
The guest OS version is Windows 7 Pro SP1 64-Bit.
The python in the guest is python 2.7.9.amd64.
I've done what you tell me to do and i've add a log.info("Successfully obtained parent PID") above return pbi[5] but no log entry at all...
I have downloaded the last build and same error occured.

**Comment by brad-sp** [comment]
Only 32-bit versions of python are currently supported in the guests.  You'll still be able to analyze 64-bit executables with the 32-bit python.  I did just make a change that should fix this problem for 64-bit python though: https://github.com/brad-accuvant/cuckoo-modified/commit/8e655f566955bbd6f21d02a9c21619de7678a5ae 

Did your update include that commit?

**Comment by ghost** [comment]
Try with Python 64-bit on guest machine but still the same error with the last build committed.
I have installed Python 32-bit and it's working perfectly.
But on the web page "Analysis Tasks", I’ve got my analyse but it's unclickable to view details about my analysis.
Thanks a lot for your help and your response time !

**Comment by brad-sp** [comment]
Can you show me a screen shot or something of what you're talking about?

**Comment by ghost** [comment]
![gitcuck](https://cloud.githubusercontent.com/assets/10134606/8087405/efd71614-0f9a-11e5-963a-79120656c7d5.png)

**Comment by brad-sp** [comment]
Hi, this is because you have enabled = no for the [reporthtml] section of reporting.conf.  Since you're using the wsgi interface instead of the (more recommended) django interface, you'll need to enable that.

**Comment by ghost** [comment]
Effectively and now Cuckoo is working like a charm.
You help me quite a lot, without you and your modified version of cuckoo, my internship would not be as good as possible.
You are the king, thanks for the help again and again.
Cordially,
Stan.

**Comment by brad-sp** [comment]
You're welcome!  I'll keep this bug in mind if we end up supporting 64-bit python in the guest, but closing it for now.
